apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-cmangos
  namespace: mangos-classic
spec:
  stripPrefix:
    prefixes:
      - /cmangos
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-cmangos-api
  namespace: mangos-classic
spec:
  stripPrefix:
    prefixes:
      - /cmangos
